#!groovy

// Generated by IBM TransformationAdvisor
// Thu Jul 04 08:07:03 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'servletsample'
    mvnCommands = '--version'
    test='false'
}